# Generated by Django 5.1.2 on 2025-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_available_from',
            field=models.TimeField(blank=True, help_text='Temporary change in start time (just for today)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_available_to',
            field=models.TimeField(blank=True, help_text='Temporary change in end time (just for today)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekday_available_from',
            field=models.TimeField(blank=True, help_text='Your weekday availability start time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekday_available_to',
            field=models.TimeField(blank=True, help_text='Your weekday availability end time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekend_available_from',
            field=models.TimeField(blank=True, help_text='Your weekend availability start time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekend_available_to',
            field=models.TimeField(blank=True, help_text='Your weekend availability end time', null=True),
        ),
    ]
