# Generated by Django 5.1.4 on 2025-01-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_profile_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
