# Generated by Django 5.1.4 on 2025-01-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_profile_manual_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manual_availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_availability_end',
        ),
    ]
