# Generated by Django 5.1.2 on 2025-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_profile_temp_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_type',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('temporary', 'Just for Today')], default='weekday', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_from',
            field=models.TimeField(blank=True, help_text='Your availability start time', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_to',
            field=models.TimeField(blank=True, help_text='Your availability end time', null=True),
        ),
    ]
