# Generated by Django 5.1.2 on 2025-01-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_profile_availability_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp_available_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp_available_to',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekday_available_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekday_available_to',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekend_available_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekend_available_to',
        ),
    ]
