# Generated by Django 5.1.4 on 2025-01-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_remove_profile_manual_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
