# Generated by Django 5.1.2 on 2025-01-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_remove_profile_temp_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='available_to',
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_from',
            field=models.TimeField(blank=True, help_text='Your temporary availability start time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_to',
            field=models.TimeField(blank=True, help_text='Your temporary availability end time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekday_from',
            field=models.TimeField(blank=True, help_text='Your weekday availability start time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekday_to',
            field=models.TimeField(blank=True, help_text='Your weekday availability end time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekend_from',
            field=models.TimeField(blank=True, help_text='Your weekend availability start time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekend_to',
            field=models.TimeField(blank=True, help_text='Your weekend availability end time', null=True),
        ),
    ]
