# Generated by Django 5.1.2 on 2025-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_remove_profile_available_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('readme', models.TextField(help_text='Project description/documentation')),
                ('deployed_url', models.URLField(blank=True)),
                ('github_url', models.URLField()),
                ('client', models.CharField(blank=True, help_text='For whom the project was built', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, to='dev.project'),
        ),
    ]
