# Generated by Django 5.1.2 on 2025-01-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_project_remove_profile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dev.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=models.TextField(),
        ),
    ]
