# Generated by Django 5.1.4 on 2025-01-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('dev', '0005_remove_profile_available_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.project')),
            ],
            options={
                'unique_together': {('project', 'developer')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='interested_developers',
            field=models.ManyToManyField(related_name='interested_projects', through='customer.ProjectRequest', to='dev.profile'),
        ),
    ]
