# Generated by Django 5.1.4 on 2025-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_projectrequest_project_interested_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='initiated_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
