# Generated by Django 5.1.4 on 2025-01-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_projectrequest_initiated_by_customer'),
        ('dev', '0005_remove_profile_available_from_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['project', 'developer', 'status'], name='customer_pr_project_52319d_idx'),
        ),
    ]
