# Generated by Django 5.1.4 on 2025-01-12 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_projectstatusrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
