# Generated by Django 5.1.4 on 2025-01-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_meetingrequest_ended_at_meetingrequest_ended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='end_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='ended_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('developer', 'Developer')], max_length=20, null=True),
        ),
    ]
