# Generated by Django 5.1.4 on 2025-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_meetingrequest_end_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='camera_toggles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='chat_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='mic_toggles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='screen_shares',
            field=models.IntegerField(default=0),
        ),
    ]
