# Generated by Django 5.1.4 on 2025-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_meetingrequest_camera_toggles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
