# Generated by Django 5.1.4 on 2025-01-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_developerrequest_updated_at_and_more'),
        ('customer', '0009_meetingrequest_stats'),
    ]

    operations = [
    ]
