# Generated by Django 5.1.4 on 2025-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_merge_20250112_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatusrequest',
            name='requester_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
    ]
